project: null
resume_id: null
name: test_run

val_check_interval: 1.0

dataset: bigbind_act
data:
  cache: true

  use_rec: true
  use_lig: true

  sna_frac: null
  only_ki_kd: false
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      knn_rad: 20
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

task: "regression"

losses:
  act_mse_lambda: 1.0

optimizer: adamw
learn_rate: 1e-5
max_epochs: 5

batch_size: 16
sampler:
  max_rec_edges: 10000
  max_lig_edges: 1000

model:

  type: outer_prod_gnn
  
  rec_encoder:
    node_embed_size: 64
    edge_embed_size: 64
    num_mpnn_layers: 2
    edge_hidden_size: 32
    out_size: 128

  lig_encoder:
    node_embed_size: 16
    edge_embed_size: 64
    num_mpnn_layers: 2
    edge_hidden_size: 32
    out_size: 128

  out_mlp_sizes: [256, 128, 64]
  dropout_rate: 0.2
